services:
    ai-server-app:
        build: ./server
        env_file:
            - ./server/.env
            - ./server/.env.production
        ports:
            - "1001:8000"
        image: abdelrahman104/ai-server:latest
        restart: unless-stopped

    client-app:
        build: ./client
        env_file:
            - ./client/.env
            - ./client/.env.production
        ports:
            - "1000:5000"
        image: abdelrahman104/client:latest
        depends_on:
            - ai-server-app
        restart: unless-stopped

    # db:
    #     image: mongo:7.0-jammy
    #     container_name: sehetna-db
    #     restart: no
    #     ports:
    #         - "27017:27017"
    #     volumes:
    #         - Sehetna-DB:/data/db

# volumes:
#   Sehetna-DB: