services:
    ai-server-app:
        build: ./server
        env_file:
            - ./server/.env
        ports:
            - "8000:8000"
        image: sehetna/ai-server:latest
        restart: no

    client-app:
        build: ./client
        env_file:
            - ./client/.env
            - ./client/.env.production
        ports:
            - "5000:5000"
        image: sehetna/client:latest
        depends_on:
            - ai-server-app
        restart: no

    # db:
    #     image: mongo:7.0-jammy
    #     container_name: sehetna-db
    #     restart: no
    #     ports:
    #         - "27017:27017"
    #     volumes:
    #         - Sehetna-DB:/data/db

# volumes:
#   Sehetna-DB: