"use client"

import { RadialChart } from "@/components/ui/charts/RadialChart"
import MetaTooltip from "@/components/ui/GlobalComponents/tooltips/MetaTooltip"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/shadcn/card"
import { usePredictionsStore } from "@/stores/map/use-predictions"
import {
    Activity,
    AlertTriangle,
    Droplets,
    HeartPulse,
    HelpCircle,
    Thermometer,
} from "lucide-react"
import { useEffect } from "react"
import { toast } from "sonner"

export default function PredictionsViewer() {
    const { simulation } = usePredictionsStore()
    const predictions = simulation?.predictions
    useEffect(() => {
        if (predictions && predictions.length > 1) {
            toast.error("Multiple predictions detected. Please refine your simulation input.")
        }
    }, [predictions])

    if (!predictions?.length || predictions.length > 1) return null

    const prediction = predictions[0]

    const chartMetrics = [
        {
            label: "Respiratory",
            value: prediction.respiratory_disease_rate.toFixed(2),
            icon: Activity,
            tooltip:
                "Estimated respiratory disease rate per 100k\n\nPredicts new or existing cases of respiratory conditions (e.g., asthma, bronchitis, COPD) per 100,000 population.\n\nReflects the potential burden of airborne pollutants, allergens, and temperature extremes on lung health.",
            color: "var(--chart-1)",
        },
        {
            label: "Cardio Mortality",
            value: prediction.cardio_mortality_rate.toFixed(2),
            icon: HeartPulse,
            tooltip:
                "Projected cardiovascular mortality rate\n\nEstimates expected deaths due to cardiovascular diseases (including ischemic heart disease and stroke) over a specified period.\n\nIntegrates environmental exposures (air quality, temperature, weather) and demographic risk factors.",
            color: "var(--chart-2)",
        },
        {
            label: "Vectorborne",
            value: prediction.vector_disease_risk_score.toFixed(2),
            icon: AlertTriangle,
            tooltip:
                "Vector-borne disease composite risk score\n\nRisk index for diseases transmitted by vectors (e.g., dengue, malaria, Zika).\n\nCombines temperature, precipitation, and humidity with historical patterns to assess the likelihood of vector proliferation.",
            color: "var(--chart-3)",
        },
        {
            label: "Waterborne",
            value: prediction.waterborne_disease_incidents.toFixed(0),
            icon: Droplets,
            tooltip:
                "Estimated waterborne disease incidents\n\nForecasts illnesses caused by contaminated water (e.g., cholera, typhoid, and diarrheal infections).\n\nConsiders water quality data, sanitation indicators, and climate factors like rainfall and flooding.",
            color: "var(--chart-4)",
        },
        {
            label: "Heat-related",
            value: prediction.heat_related_admissions.toFixed(0),
            icon: Thermometer,
            tooltip:
                "Heat-related hospital admissions\n\nProjects hospitalizations due to heat stress or illnesses (e.g., heatstroke and dehydration).\n\nIncorporates temperature extremes, consecutive hot days, and population vulnerability.",
            color: "var(--chart-5)",
        },
    ]

    return (
        <Card className="border-none bg-transparent shadow-none">
            <CardHeader className="flex flex-row justify-between pt-4 pb-0">
                <CardTitle className="text-lg font-semibold">Simulation Result</CardTitle>
                {/* help icon */}
                <MetaTooltip
                    title="Simulation Projections"
                    description={
                        <div className="text-muted-foreground mt-2 text-xs">
                            Predicted health risk scores generated by a{" "}
                            <strong>LightGBM model</strong> using environmental, climate, and
                            socioeconomic indicators.
                            <br />
                            <br />
                            <ul>
                                <li>
                                    <strong>Respiratory Disease Rate</strong>: Lung disease burden
                                    from air pollution
                                </li>
                                <li>
                                    <strong>Cardio Mortality Rate</strong>: Cardiovascular death
                                    risk from heat and pollution
                                </li>
                                <li>
                                    <strong>Vector Disease Risk Score</strong>: Outbreak likelihood
                                    of insect-borne diseases
                                </li>
                                <li>
                                    <strong>Waterborne Disease Incidents</strong>: Water
                                    contamination risk linked to floods
                                </li>
                                <li>
                                    <strong>Heat-Related Admissions</strong>: Hospital admissions
                                    driven by extreme heat
                                </li>
                            </ul>
                        </div>
                    }
                    trigger={
                        <HelpCircle className="text-muted-foreground hover:text-foreground h-4 w-4 cursor-pointer" />
                    }
                />
            </CardHeader>
            <CardContent className="grid grid-cols-3 p-0 pb-4">
                {chartMetrics.map((metric) => (
                    <RadialChart
                        key={metric.label}
                        value={metric.value}
                        color={metric.color}
                        chartLabel={metric.label}
                        Icon={metric.icon}
                        tooltip={metric.tooltip}
                        max={100}
                    />
                ))}
            </CardContent>
        </Card>
    )
}
